version: 2.1
description: "An orb wrapper for the infracost CLI tool"
display:
  source_url: https://github.com/infracost/infracost-orb

aliases:
  - &terraform_file_directory_param
    type: string
    default: terraform/
    description: The root directory of your terraform file
  - &infracost_report_directory_param
    type: string
    default: /tmp/infracost/
    description: The CircleCI workspace directory where to persist the `infracost.json` JSON report. Use `attach_workspace` to access the report.

executors:
  infracost_executor:
    docker:
      - image: infracost/infracost:latest

jobs:
  run-infracost-report:
    executor: infracost_executor
    parameters:
      terraform_file_directory: *terraform_file_directory_param
    steps:
      - checkout
      - run-infracost-report

commands:
  run-infracost-report:
    parameters:
      terraform_file_directory: *terraform_file_directory_param
    steps:
      - run: infracost --tfdir <<parameters.terraform_file_directory>>
