version: 2.1
description: "Show cloud cost estimate changes for Terraform in pull requests."
display:
  home_url: https://www.infracost.io
  source_url: https://github.com/infracost/infracost-orb
jobs:
  infracost:
    docker:
      - image: infracost/infracost:latest
    parameters:
      path:
        description: Path to the Terraform directory or JSON/plan file. Either `path` or `config_file` is required.
        default: ""
        type: string
      terraform_plan_flags:
        description: Flags to pass to the 'terraform plan' command, e.g. `"-var-file=my.tfvars -var-file=other.tfvars"`. Applicable when path is a Terraform directory.
        default: ""
        type: string
      terraform_workspace:
        description: The Terraform workspace to use. Applicable when path is a Terraform directory. Only set this for multi-workspace deployments, otherwise it might result in the Terraform error "workspaces not supported".
        default: ""
        type: string
      usage_file:
        description: Path to Infracost usage file (https://www.infracost.io/docs/usage_based_resources) that specifies values for usage-based resources, see https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml for the available options.
        default: ""
        type: string
      config_file:
        description: If your repo has multiple Terraform projects or workspaces, define them in a config file (https://www.infracost.io/docs/config_file/) and set this input to its path. Their results will be combined into the same diff output. Cannot be used with path, terraform_plan_flags or usage_file inputs.
        default: ""
        type: string
      percentage_threshold:
        description: The absolute percentage threshold that triggers a pull request comment with the diff. Defaults to 0, meaning that a comment is posted if the cost estimate changes. For example, set to 5 to post a comment if the cost estimate changes by more than plus or minus 5%.
        default: "0"
        type: string
    environment:
      path: << parameters.path >>
      terraform_plan_flags: << parameters.terraform_plan_flags >>
      terraform_workspace: << parameters.terraform_workspace >>
      usage_file: << parameters.usage_file >>
      config_file: << parameters.config_file >>
      percentage_threshold: << parameters.percentage_threshold >>
    steps:
      - checkout
      - run: /scripts/ci/diff.sh

examples:
  infracost:
    description: Show cloud cost estimate changes for Terraform in pull requests.
    usage:
      version: 2.1
      orbs:
        infracost: infracost/infracost@0.6.0
      workflows:
        main:
          jobs:
            - infracost/infracost:
                path: path/to/code
                terraform_plan_flags: -var-file=my.tfvars
