version: 2.1
description: "Show cloud cost estimate changes for Terraform in pull requests."
display:
  home_url: https://www.infracost.io
  source_url: https://github.com/infracost/infracost-orb
jobs:
  infracost:
    docker:
      - image: infracost/infracost:latest
    parameters:
      path:
        description: Path to the Terraform directory or JSON/plan file. Either `path` or `config_file` is required.
        default: ""
        type: string
      terraform_plan_flags:
        description: Flags to pass to the 'terraform plan' command, e.g. `"-var-file=my.tfvars -var-file=other.tfvars"`. Applicable when path is a Terraform directory.
        default: ""
        type: string
      terraform_workspace:
        description: The Terraform workspace to use. Applicable when path is a Terraform directory. Only set this for multi-workspace deployments, otherwise it might result in the Terraform error "workspaces not supported".
        default: ""
        type: string
      usage_file:
        description: Path to Infracost usage file (https://www.infracost.io/docs/usage_based_resources) that specifies values for usage-based resources, see https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml for the available options.
        default: ""
        type: string
      config_file:
        description: If your repo has multiple Terraform projects or workspaces, define them in a config file (https://www.infracost.io/docs/config_file/) and set this input to its path. Their results will be combined into the same diff output. Cannot be used with path, terraform_plan_flags or usage_file inputs.
        default: ""
        type: string
      post_condition:
        description: |
          A JSON string describing the condition that triggers pull request comments, can be one of these:
          - `'{"update": true}'`: we suggest you start with this option. When a commit results in a change in cost estimates vs earlier commits, the integration will create **or update** a PR comment (not commit comments). The GitHub comments UI can be used to see when/what was changed in the comment. PR followers will only be notified on the comment create (not update), and the comment will stay at the same location in the comment history. This is initially supported for GitHub, please let us know if you'd like to see this for GitLab and BitBucket.
          - `'{"has_diff": true}'`: a commit comment is put on the first commit with a Terraform change (i.e. there is a diff) and on every subsequent commit (regardless of whether or not there is a Terraform change in the particular commit). This is the default behavior but we think `update` might be a better default so we might change this in the future.
          - `'{"always": true}'`: a commit comment is put on every commit.
          - `'{"percentage_threshold": 0}'`: absolute percentage threshold that triggers a comment. For example, set to 1 to post a comment if the cost estimate changes by more than plus or minus 1%. A commit comment is put on every commit with a Terraform change that results in a cost diff that is bigger than the threshold.
        default: '{"has_diff": true}'
        type: string
      show_skipped:
        description: Show unsupported resources, some of which might be free, at the bottom of the Infracost output.
        default: "false"
        type: string
    environment:
      path: << parameters.path >>
      terraform_plan_flags: << parameters.terraform_plan_flags >>
      terraform_workspace: << parameters.terraform_workspace >>
      usage_file: << parameters.usage_file >>
      config_file: << parameters.config_file >>
      post_condition: << parameters.post_condition >>
      show_skipped: << parameters.show_skipped >>
    steps:
      - checkout
      - run: /scripts/ci/diff.sh

examples:
  infracost:
    description: Show cloud cost estimate changes for Terraform in pull requests.
    usage:
      version: 2.1
      orbs:
        infracost: infracost/infracost@0.8.2
      workflows:
        main:
          jobs:
            - infracost/infracost:
                path: path/to/code
                terraform_plan_flags: -var-file=my.tfvars
