version: 2.1
description: "Show cloud cost estimate changes for Terraform in pull requests."
display:
  home_url: https://www.infracost.io
  source_url: https://github.com/infracost/infracost-orb
jobs:
  infracost:
    docker:
      - image: infracost/infracost:latest
    parameters:
      terraform_json_file:
        description: Path to Terraform plan JSON file.
        default: ""
        type: string
      terraform_plan_file:
        description: Path to Terraform plan file relative to 'terraform_dir'. Requires 'terraform_dir' to be set.
        default: ""
        type: string
      terraform_use_state:
        description: Use Terraform state instead of generating a plan.
        default: "false"
        type: string
      terraform_dir:
        description: Path to the Terraform code directory (default is current working directory).
        default: "."
        type: string
      terraform_plan_flags:
        description: Flags to pass to the 'terraform plan' command, e.g. `"-var-file=myvars.tfvars"`.
        default: ""
        type: string
      percentage_threshold:
        description: The absolute percentage threshold that triggers a pull request comment with the diff. Defaults to 0, meaning that a comment is posted if the cost estimate changes. For example, set to 5 to post a comment if the cost estimate changes by plus or minus 5%.
        default: "0"
        type: string
      pricing_api_endpoint:
        description: Specify an alternate Cloud Pricing API URL (default is https://pricing.api.infracost.io).
        default: ""
        type: string
      usage_file:
        description: Path to Infracost usage file that specifies values for usage-based resources.
        default: ""
        type: string
    environment:
      terraform_json_file: << parameters.terraform_json_file >>
      terraform_plan_file: << parameters.terraform_plan_file >>
      terraform_use_state: << parameters.terraform_use_state >>
      terraform_dir: << parameters.terraform_dir >>
      terraform_plan_flags: << parameters.terraform_plan_flags >>
      percentage_threshold: << parameters.percentage_threshold >>
      pricing_api_endpoint: << parameters.pricing_api_endpoint >>
      usage_file: << parameters.usage_file >>
    steps:
      - checkout
      - run: /scripts/ci/diff.sh

examples:
  infracost:
    description: Show cloud cost estimate changes for Terraform in pull requests.
    usage:
      version: 2.1
      orbs:
        infracost: infracost/infracost@0.5.0
      workflows:
        main:
          jobs:
            - infracost/infracost:
                terraform_dir: path/to/code
                terraform_plan_flags: -var-file=myvars.tfvars
