version: 2.1
description: "An orb wrapper for the infracost CLI tool"
display:
  source_url: https://github.com/infracost/infracost-orb

aliases:
  - &terraform_file_directory_param
    type: string
    default: terraform/
    description: The root directory of your terraform file
  - &infracost_report_directory_param
    type: string
    default: /tmp/infracost/
    description: The CircleCI workspace directory where to persist the `infracost.json` JSON report. Use `attach_workspace` to access the report.

executors:
  infracost_executor:
    docker:
      - image: infracost/infracost:latest

jobs:
  run-infracost-report:
    executor: infracost_executor
    parameters:
      terraform_file_directory: *terraform_file_directory_param
    steps:
      - checkout
      - run-infracost-report
  save-infracost-json:
    executor: infracost_executor
    parameters:
      terraform_file_directory: *terraform_file_directory_param
      infracost_report_directory: *infracost_report_directory_param
    steps:
      - checkout
      - save-infracost-json

commands:
  run-infracost-report:
    parameters:
      terraform_file_directory: *terraform_file_directory_param
    steps:
      - run: infracost --tfdir <<parameters.terraform_file_directory>>

examples:
  print_and_parse_report:
    description: Run a tabular report and parse the saved JSON output, this example the plan file is already committed to the repository, it's recommended you run plan to create the report as part of this workflow.
    usage:
      version: 2.1
      orbs:
        infracost: infracost/infracost@0.0.6
      jobs:
        read-report:
          docker:
            - image: endeveit/docker-jq
          steps:
            - attach_workspace:
                at: ~/report
            - run:
                name: Read JSON report
                command: cat ~/report/infracost.json | jq
      workflows:
        print_and_parse_report:
          jobs:
            - infracost/run-infracost-report:
                terraform_plan_file: plan.save
                terraform_file_directory: terraform/
            - infracost/save-infracost-json:
                terraform_plan_file: plan.save
                terraform_file_directory: terraform/
                infracost_report_directory: ~/report
            - read-report:
                requires:
                  - infracost/save-infracost-json
